// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.20.3
// source: spam_detector.proto

package spam_detector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanResponse_Result int32

const (
	ScanResponse_UNKNOWN ScanResponse_Result = 0
	ScanResponse_HAM     ScanResponse_Result = 1
	ScanResponse_SPAM    ScanResponse_Result = 2
)

// Enum value maps for ScanResponse_Result.
var (
	ScanResponse_Result_name = map[int32]string{
		0: "UNKNOWN",
		1: "HAM",
		2: "SPAM",
	}
	ScanResponse_Result_value = map[string]int32{
		"UNKNOWN": 0,
		"HAM":     1,
		"SPAM":    2,
	}
)

func (x ScanResponse_Result) Enum() *ScanResponse_Result {
	p := new(ScanResponse_Result)
	*p = x
	return p
}

func (x ScanResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_spam_detector_proto_enumTypes[0].Descriptor()
}

func (ScanResponse_Result) Type() protoreflect.EnumType {
	return &file_spam_detector_proto_enumTypes[0]
}

func (x ScanResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanResponse_Result.Descriptor instead.
func (ScanResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_spam_detector_proto_rawDescGZIP(), []int{1, 0}
}

type ScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spam_detector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spam_detector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_spam_detector_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ScanResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=spam_detector.ScanResponse_Result" json:"result,omitempty"`
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spam_detector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spam_detector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_spam_detector_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetResult() ScanResponse_Result {
	if x != nil {
		return x.Result
	}
	return ScanResponse_UNKNOWN
}

var File_spam_detector_proto protoreflect.FileDescriptor

var file_spam_detector_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x70, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x70, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x22, 0x27, 0x0a, 0x0b, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x74, 0x0a,
	0x0c, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e,
	0x73, 0x70, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x28, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x48, 0x41, 0x4d, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x50, 0x41,
	0x4d, 0x10, 0x02, 0x32, 0x51, 0x0a, 0x0c, 0x53, 0x70, 0x61, 0x6d, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x41, 0x0a, 0x04, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x1a, 0x2e, 0x73, 0x70,
	0x61, 0x6d, 0x5f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x70, 0x61, 0x6d, 0x5f, 0x64,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x74, 0x6f, 0x72, 0x6f, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x63, 0x73, 0x75, 0x64, 0x68, 0x2e, 0x65, 0x64, 0x75, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spam_detector_proto_rawDescOnce sync.Once
	file_spam_detector_proto_rawDescData = file_spam_detector_proto_rawDesc
)

func file_spam_detector_proto_rawDescGZIP() []byte {
	file_spam_detector_proto_rawDescOnce.Do(func() {
		file_spam_detector_proto_rawDescData = protoimpl.X.CompressGZIP(file_spam_detector_proto_rawDescData)
	})
	return file_spam_detector_proto_rawDescData
}

var file_spam_detector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spam_detector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spam_detector_proto_goTypes = []interface{}{
	(ScanResponse_Result)(0), // 0: spam_detector.ScanResponse.Result
	(*ScanRequest)(nil),      // 1: spam_detector.ScanRequest
	(*ScanResponse)(nil),     // 2: spam_detector.ScanResponse
}
var file_spam_detector_proto_depIdxs = []int32{
	0, // 0: spam_detector.ScanResponse.result:type_name -> spam_detector.ScanResponse.Result
	1, // 1: spam_detector.SpamDetector.Scan:input_type -> spam_detector.ScanRequest
	2, // 2: spam_detector.SpamDetector.Scan:output_type -> spam_detector.ScanResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spam_detector_proto_init() }
func file_spam_detector_proto_init() {
	if File_spam_detector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spam_detector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spam_detector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spam_detector_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spam_detector_proto_goTypes,
		DependencyIndexes: file_spam_detector_proto_depIdxs,
		EnumInfos:         file_spam_detector_proto_enumTypes,
		MessageInfos:      file_spam_detector_proto_msgTypes,
	}.Build()
	File_spam_detector_proto = out.File
	file_spam_detector_proto_rawDesc = nil
	file_spam_detector_proto_goTypes = nil
	file_spam_detector_proto_depIdxs = nil
}
