# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spam_detector.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13spam_detector.proto\x12\rspam_detector\"\x1e\n\x0bScanRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"l\n\x0cScanResponse\x12\x32\n\x06result\x18\x01 \x01(\x0e\x32\".spam_detector.ScanResponse.Result\"(\n\x06Result\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03HAM\x10\x01\x12\x08\n\x04SPAM\x10\x02\x32Q\n\x0cSpamDetector\x12\x41\n\x04Scan\x12\x1a.spam_detector.ScanRequest\x1a\x1b.spam_detector.ScanResponse\"\x00\x42-Z+torospace.csudh.edu/api/proto/spam_detectorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spam_detector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+torospace.csudh.edu/api/proto/spam_detector'
  _globals['_SCANREQUEST']._serialized_start=38
  _globals['_SCANREQUEST']._serialized_end=68
  _globals['_SCANRESPONSE']._serialized_start=70
  _globals['_SCANRESPONSE']._serialized_end=178
  _globals['_SCANRESPONSE_RESULT']._serialized_start=138
  _globals['_SCANRESPONSE_RESULT']._serialized_end=178
  _globals['_SPAMDETECTOR']._serialized_start=180
  _globals['_SPAMDETECTOR']._serialized_end=261
# @@protoc_insertion_point(module_scope)
